name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login --username $DOCKER_USER --password-stdin < $DOCKER_PASSWORD
      - name: Build the Docker image
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
        run: |
          docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/bash-webserver:$(date +%s)
      - name: Docker push
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
        run: |
          docker push ${{secrets.DOCKER_USER}}/bash-webserver
